version: '2'
services:
    bylaw_report-app:
        image: bylaw_report
        external_links:
            - bylaw_report-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/bylaw_report?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bylaw_report-mysql:
        extends:
            file: mysql.yml
            service: bylaw_report-mysql
